services:
  web:
    image: presentationlayer:latest
    container_name: my_cool_app_v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # HTTP
      - "8443:443" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=Library;User=myuser;Password=123456;
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Library
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
